### ISSUE TITLE
Down For Life - Name and Date when scrolled over

### ISSUE THREAD

**Issue by justingotthardt** [beeasyboards/beeasyboards#1]
I would love if:
## When you scroll over the DFL pics they will fade and text will fade in with the persons name and a "down since _date_".  When the DFL pic is clicked it opens a new window into the persons instagram or website.  

THX BAE<3
-justin

**Comment by scottbedard** [comment]
@justingotthardt The linking aspect of this will be the same as it is now. We already have controls in the backend to link these to where ever you want, and a switch to determine if it should be in a new window. I'll go ahead and set the default to be a new window though.

What kind of format do you want for the date?
Down since 2014
Down since August 2014
Down since Aug 9, '14
etc..

**Comment by justingotthardt** [comment]
Down since August 2014

_be easy,_
-Justin Gotthardt
www.beeasyboards.com
www.facebook.com/beeasyboards
